Hw12 calendar
NoisyPunk/otus_go_hw pull request #12
Opened 2024-03-11 11:48 UTC by NoisyPunk

## Домашнее задание №12 «Заготовка сервиса Календарь»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Понятность и чистота кода (включая факт, что проект разбит
на пакеты по определенной логике) - до 2 баллов
- [ ] Реализовано конфигурирование сервиса - 1 балл
- [ ] Используется логгер и он настраивается из конфига - 1 балл
- [ ] Запускается простой HTTP-сервер, мидлвара удовлетворяет ТЗ - 1 балл
- [ ] Присутствуют юнит-тесты - 1 балл

Реализовано хранилище:
- [ ] in-memory - 1 балл
- [ ] sql + миграции - 2 балла

#### Зачёт от 7 баллов

2024-03-12 04:48 UTC, dshemin requested changes

2024-03-12 04:48 UTC, dshemin commented on .golangci.yml
> -    - depguard
Критично:

Не вносите изменения в правила линтера.

2024-03-12 04:48 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +	&& goose -dir migrations postgres "host=127.0.0.1 port=5436 user=postgres password=postgres dbname=calendar sslmode=disable" up \
Важно:

Миграции можно собрать в отдельный контейнер и запускать их по готовности БД. Например так https://github.com/gomicro/docker-goose

2024-03-12 04:48 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +	go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
Важно:

Надо ставить не lates а именно 1.50.1

2024-03-12 04:48 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	ctx, cancel := signal.NotifyContext(ctx,
Важно:

Это надо перенести в самое начало, чтобы создавать создавать контекст с логерам на основании этого контекста и мы могли прервать работу календаря.

2024-03-12 04:48 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +	l := logger.FromContext(ctx)
Важно:

Если нам конекст тут нужен только для того, чтобы передать логер, то стоит просто передать логер.

2024-03-12 04:48 UTC, dshemin commented on hw12_13_14_15_calendar/internal/configs/config.go
> +		logg.Fatal(err.Error())
Важно:

Верните эти ошибки в вызвающий код и обрабатывайте там.

2024-03-12 04:48 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +		_, _, _ = next, w, r
Критично:

Не реализовано.

```
Информация об обработанном запросе должна выводиться в log-файл:

IP клиента;
дата и время запроса;
метод, path и версия HTTP;
код ответа;
latency (время обработки запроса, посчитанное, например, с помощью middleware);
user agent, если есть.
```

2024-03-12 04:48 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	_ = ctx
Критично:

Не реализовано.

2024-03-12 04:48 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	_ = r
Важно:

Просто сделайте такую сигнатуру:
`getHello(w http.ResponseWriter, _ *http.Request)`

2024-03-12 04:48 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	l := logger.FromContext(ctx)
Важно:

Тут тоже надо лочить мютекс.

2024-03-12 04:48 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	l := logger.FromContext(ctx)
Важно:

Тут тоже надо лочить мютекс.

2024-03-12 04:48 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	l := logger.FromContext(ctx)
Важно:

Тут тоже надо лочить мютекс.

2024-03-19 18:00 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	l := logger.FromContext(ctx)
Исправлено

2024-03-19 18:00 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	l := logger.FromContext(ctx)
Исправлено

2024-03-19 18:00 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	l := logger.FromContext(ctx)
Исправлено

2024-03-19 18:02 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	_ = r
Исправлено

2024-03-19 18:29 UTC, NoisyPunk commented on hw12_13_14_15_calendar/Makefile
> +	go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
<img width="1095" alt="image" src="https://github.com/NoisyPunk/otus_go_hw/assets/62419821/7cb41401-0d3c-4809-89d3-d518f337bf33">
C 1.50.1, получаю и локально и в си вот такую ошибку, пока что не понимаю как ее победить 
https://github.com/golangci/golangci-lint/issues/3533 здесь и в смежных тасках пишут что вроде бы она уже побеждена, но я не понимаю что делаю не так, может быть вы с этим сталкивались?

2024-03-19 18:31 UTC, NoisyPunk commented on .golangci.yml
> -    - depguard
Исправлено

2024-03-19 18:34 UTC, NoisyPunk commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	ctx, cancel := signal.NotifyContext(ctx,
Исправлено

2024-03-19 18:35 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/app/app.go
> +	l := logger.FromContext(ctx)
Исправлено

2024-03-19 18:40 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/configs/config.go
> +		logg.Fatal(err.Error())
Исправлено

2024-03-20 21:40 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +		_, _, _ = next, w, r
Исправлено

2024-03-20 22:17 UTC, NoisyPunk commented on hw12_13_14_15_calendar/Makefile
> +	&& goose -dir migrations postgres "host=127.0.0.1 port=5436 user=postgres password=postgres dbname=calendar sslmode=disable" up \
Постараюсь исправить во время работы над следующим ДЗ, если можно, поскольку очень уж растянул это

2024-03-20 22:17 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	_ = ctx
Исправлено

2024-03-22 03:26 UTC, dshemin requested changes

2024-03-22 03:26 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +	go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
Скорее всего надо бампнуть версию линтера.

2024-03-22 03:26 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		panic(err)
Важно:

Не используйте панику никогда в коде. Напечатайте ошибку и вызовите os.Exit(1)

2024-03-22 03:26 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +		l.Info(
Критично:

Нет статуса ответа. Внимательно посмотрите ДЗ.

2024-03-22 21:36 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +		l.Info(
Исправлено

2024-03-22 21:36 UTC, NoisyPunk commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		panic(err)
Исправлено

2024-03-23 07:54 UTC, dshemin approved these changes

2024-03-23 08:25 UTC, merged