Hw15 calendar
NoisyPunk/otus_go_hw pull request #15
Opened 2024-04-13 16:22 UTC by NoisyPunk

## Домашнее задание №15 «Докеризация и интеграционное тестирование Календаря»

### Критерии оценки
- [ ] Проект полностью запускается и останавливается с помощью `make up` / `make down` - 3 балла
- [ ] Интеграционные тесты запускаются с помощью `make integration-tests`. Команда возвращает верный код ответа - 1 балл

Интеграционные тесты покрывают бизнес сценарии:
- [ ] добавление события и обработка бизнес ошибок - 2 балла
- [ ] получение листинга событий на день/неделю/месяц - 2 балла
- [ ] отправка уведомлений - 2 балла

#### Зачёт от 7 баллов

Скриншоты вывода make integration-tests:
С фейлом:
![image](https://github.com/NoisyPunk/otus_go_hw/assets/62419821/c6364bb9-e7fe-4db0-809c-ec39e4cd9e52)
Успешный:
![image](https://github.com/NoisyPunk/otus_go_hw/assets/62419821/23d2d32a-7e0a-4ff4-9ae7-d5aecfbf62d5)

2024-04-14 04:36 UTC, dshemin requested changes

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/docker-compose.yml
> +    image: calendar:latest
Критично:

Используется некий образ, а как его собрать?  Из-за него, при попытке запуска `make integration-tests`. Всё падает так, как у меня нет этого образа и в итоге я не могу запустить интеграционные тесты. Опишите тут секцию `build`.

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/configs/scheduler_config.yaml
> +user: user
Важно:

Если нам понадобится соединение с ещё одним сервисом у которого тоже надо будет указать пользователя, пароль, хост и пароль. В итоге надо будет что-то менять. Либо добавьте префикс к полям как-то так:

```
rmq_user: user
rmq_password: pass
...
```

Либо использовать вложенность:

```
rmq:
    user: user
    password: pass
    ...
```

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/sender/app.go
> +				l.Error("can't unmarshal message",
Важно:
После логирование надо добавить continue. Иначе мы залогируем ошибку и потом будем обрабатывать сообщение.

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/internal/configs/scheduler_config/scheduler_config.go
> +func newConfig() *Config {
Важно:

Ненужная функция.

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/internal/configs/sender_config/sender_config.go
>  func newConfig() *Config {
Важно:

Ненужная функция.

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/internal/queue/consumer.go
> +	RmqChannel    *amqp.Channel
Важно:

Мы точно хотим дать внешним пакетам возможность обращаться к этой переменной? Если да - то у нас протекает абстракция.

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/internal/queue/consumer.go
> +		log.Error("consumer connection to rmq failed")
Важно:

Либо логируйте, либо возвращайте. Делать одновременно не надо.

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/internal/queue/producer.go
> +		log.Error("producer connection to rmq failed")
Важно:

Либо логируйте, либо возвращайте.

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/internal/queue/producer.go
> +	RmqChannel    *amqp.Channel
Важно:

Точно это свойство должно быть публичным?

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/event_storage.go
> +	Duration     int       `db:"duration"`
Важно:

Лучше вернуть тут time.Duration

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/event_storage.go
> +	TimeToNotify int       `db:"time_to_notify"`
Важно:

Если это точное время когда надо нотифицировать то нужно time.Time. Если время через сколько нотифицировать - time.Duration

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	DB *sqlx.DB
Важно:

Данное свойство точно должно стать публичным?

2024-04-14 04:36 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	l := logger.FromContext(ctx)
Важно:

В итоге мы достаём идентификаторы всех просроченных событий и потом по одном удаляем. Получаем N + 1 запрос. Что будет если просроченных смобытий будет 1_000_000? Это можно сделать за один запрос к БД.

2024-04-14 21:01 UTC, NoisyPunk commented on hw12_13_14_15_calendar/docker-compose.yml
> +    image: calendar:latest
Исправлено

2024-04-14 21:27 UTC, NoisyPunk commented on hw12_13_14_15_calendar/configs/scheduler_config.yaml
> +user: user
Исправлено

2024-04-14 21:29 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/configs/scheduler_config/scheduler_config.go
> +func newConfig() *Config {
Исправлено

2024-04-14 21:29 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/configs/sender_config/sender_config.go
>  func newConfig() *Config {
Исправлено

2024-04-16 15:04 UTC, NoisyPunk commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	l := logger.FromContext(ctx)
Исправлено

2024-05-02 20:19 UTC, merged