Hw08 envdir tool
NoisyPunk/otus_go_hw pull request #8
Opened 2024-02-11 21:28 UTC by NoisyPunk

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-02-12 07:20 UTC, dshemin requested changes

2024-02-12 07:20 UTC, dshemin commented on hw08_envdir_tool/testdata/env/EMPTY
> -
Критично:

Тестовые данные и уже написанные тесты менять нельзя.

2024-02-12 07:20 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +	command.Stdout = os.Stdout
Критично:

Нет перенаправления Stdio, stderr.

2024-02-12 07:20 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +		log.Fatal(err)
Критично:

Не возвращается статус код вызванной программы.

2024-02-12 07:20 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +		data, err := os.ReadFile(filePath)
Важно:

Мы вычитываем весь файл в память ради только первой строки - не оптимально.

2024-02-12 16:22 UTC, NoisyPunk commented on hw08_envdir_tool/testdata/env/EMPTY
> -
Исправил

2024-02-12 16:22 UTC, NoisyPunk commented on hw08_envdir_tool/executor.go
> +	command.Stdout = os.Stdout
Исправил

2024-02-12 16:22 UTC, NoisyPunk commented on hw08_envdir_tool/executor.go
> +		log.Fatal(err)
Кажется исправил

2024-02-12 16:22 UTC, NoisyPunk commented on hw08_envdir_tool/env_reader.go
> +		data, err := os.ReadFile(filePath)
Поковырялся, нашел что у bufio есть построчное чтение, наверное это ключ?

2024-02-13 05:52 UTC, dshemin requested changes

2024-02-13 05:52 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +		log.Fatal(err)
Увы но нет, если программа завершилась с ошибкой то мы тоже должны вернуть статус код. Подсказка, посмотрите какой тип ошибки нам вернётся тут.

2024-02-13 20:32 UTC, NoisyPunk commented on hw08_envdir_tool/executor.go
> +		log.Fatal(err)
Тип ошибки там exec.ExitError и получим мы ее если в скрипте чтот прошло не по плану, но судя по описанию можем и не только ее, поэтому видимо нужен еще какой-то дефолтный код ошибки? Или опять не в ту сторону думаю?

2024-02-14 17:15 UTC, dshemin requested changes

2024-02-14 17:15 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +			exitError.ExitCode()
Критично:

Тут вы просто получите значение, а его ещё вернуть надо. Обращайте внимание на сигнатуры функций

https://pkg.go.dev/os#ProcessState.ExitCode

2024-02-14 18:10 UTC, NoisyPunk commented on hw08_envdir_tool/executor.go
> +			exitError.ExitCode()
Прошу прощения, тут действительно внимательность уже решила уснуть

2024-02-15 01:27 UTC, dshemin approved these changes

2024-02-15 07:22 UTC, merged